name: WPR
version: "0.1"
license: "GPL-2.0-or-later"
date: 2021-06-09
description: |
    Wreath Product Recognition implements constructive recognition algorithms for wreath products with almost simple base component

authors:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

maintainers:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

GAP: ">= 4.11"

www: https://FriedrichRober.github.io/WPR/
readme: README.md
packageinfo: https://FriedrichRober.github.io/WPR/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/FriedrichRober/WPR/releases/download/v0.1/WPR-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Rob21</span>]   <b class='BibAuthor'>Rober, F.</b>,
     <i class='BibTitle'>WPR, Wreath Product Recognition implements constructive recognition algorithms for wreath products with almost simple base component,
             Version 0.1</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://FriedrichRober.github.io/WPR/">https://FriedrichRober.github.io/WPR/</a></span>.
    </p>
    

bibtex: |
    @misc{ WPR0.1,
      author =           {Rober, F.},
      title =            {{WPR},  Wreath  Product  Recognition  implements constructive
                          recognition algorithms for wreath products with almost simple
                          base component, {V}ersion 0.1},
      month =            {Jun},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href                 {https://FriedrichRober.github.io/WPR/}
                          {\texttt{https://FriedrichRober.github.io/}\discretionary
                          {}{}{}\texttt{WPR/}}},
      printedkey =       {Rob21}
    }

